clients/urls.py
from django.urls import path

from clients.views import ClientRequestCreateView

app_name = 'clients'

urlpatterns = [
    path('create/', ClientRequestCreateView.as_view(), name='create'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('robots.txt/', TemplateView.as_view(
        template_name='robots.txt', content_type='text/plain',
    )),
    path('clients/', include('clients.urls', namespace='clients')),
    path('', include('landing.urls', namespace='landing')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landing/urls.py
from django.urls import path

from landing.views import (
    CertificatesView, CoursesView, IndexView, MassageDetailView,
)

app_name = 'landing'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('certificates/', CertificatesView.as_view(), name='certificates'),
    path('courses/', CoursesView.as_view(), name='courses'),
    path('<slug:slug>/', MassageDetailView.as_view(),
         name='massage_detail'),
]

landing/models/course.py
from django.db import models


class Course(models.Model):
    name = models.CharField(verbose_name='Название', max_length=100)
    position = models.PositiveIntegerField(verbose_name='Позиция', default=0)
    old_price = models.PositiveIntegerField(
        verbose_name='Стоимость без скидки',
    )
    price = models.PositiveIntegerField(verbose_name='Стоимость')
    description = models.TextField(verbose_name='Описание')
    is_active = models.BooleanField(verbose_name='Активен', default=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['position']

landing/models/course_testimonial.py
from django.db import models

from .testimonial import Testimonial


class CourseTestimonialManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(
            related_with=Testimonial.RelatedWith.COURSES,
        )


class CourseTestimonial(Testimonial):
    objects = CourseTestimonialManager()

    class Meta:
        proxy = True

landing/models/discount.py
from django.db import models
from django.utils import timezone


class Discount(models.Model):
    class Target(models.TextChoices):
        MASSAGES = 'massages', 'Массажи'
        COURSES = 'courses', 'Курсы'
        CERTIFICATES = 'certificates', 'Сертификаты'

    target = models.CharField(
        verbose_name='Скидка действует на', max_length=100, unique=True,
        choices=Target.choices, default=Target.MASSAGES,
    )
    percent = models.PositiveIntegerField(
        verbose_name='Процент скидки', default=0,
    )
    deadline = models.DateTimeField(verbose_name='Дата и время окончания')

    @property
    def seconds_left(self):
        now = timezone.now()

        if now <= self.deadline:
            return (self.deadline - now).total_seconds()

    def __str__(self):
        return self.target

landing/models/massage.py
from ckeditor.fields import RichTextField
from django.db import models
from django.urls import reverse


class Massage(models.Model):
    slug = models.SlugField(verbose_name='Путь в адресной строке')
    name = models.CharField(verbose_name='Название', max_length=100)
    short_description = models.TextField(verbose_name='Краткое описание')
    duration = models.CharField(verbose_name='Длительность', max_length=100)
    description = RichTextField(verbose_name='Описание')
    old_price = models.PositiveIntegerField(
        verbose_name='Стоимость без скидки',
    )
    price = models.PositiveIntegerField(verbose_name='Стоимость')
    is_active = models.BooleanField(verbose_name='Активен', default=True)
    thumbnail = models.ImageField(
        verbose_name='Картинка на карточке', upload_to='massage_thumbnails',
    )
    image = models.ImageField(
        verbose_name='Картинка на фоне', upload_to='massage_images',
    )
    position = models.PositiveIntegerField(verbose_name='Позиция', default=0)

    def get_page_url(self):
        return reverse('landing:massage_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['position']

landing/models/massage_result.py
from django.core.exceptions import ValidationError
from django.db import models


class MassageResult(models.Model):
    massage = models.ForeignKey(
        verbose_name='Массаж', to='landing.Massage', related_name='results',
        on_delete=models.CASCADE,
    )
    image = models.ImageField(
        verbose_name='Картинка', upload_to='massage_result_images', null=True,
        blank=True,
    )
    video_url = models.TextField(
        verbose_name='Ссылка на видео', null=True, blank=True,
    )
    position = models.PositiveIntegerField(verbose_name='Позиция', default=0)

    def clean(self):
        super().clean()
        if any([
            self.image and self.video_url,
            not self.image and not self.video_url
        ]):
            raise ValidationError('One of image and video url must be filled')

    class Meta:
        ordering = ['position']

landing/models/specialist.py
from django.db import models


class Specialist(models.Model):
    first_name = models.CharField(verbose_name='Имя', max_length=100)
    last_name = models.CharField(verbose_name='Фамилия', max_length=100)
    image = models.ImageField(
        verbose_name='Картинка', upload_to='specialist_images',
    )
    position = models.PositiveIntegerField(verbose_name='Позиция', default=0)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        ordering = ['position']

landing/models/testimonial.py
from django.core.exceptions import ValidationError
from django.db import models


class TestimonialManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(related_with__isnull=True)


class Testimonial(models.Model):
    class RelatedWith(models.TextChoices):
        COURSES = 'courses', 'Курсы'

    image = models.ImageField(
        verbose_name='Картинка', upload_to='testimonial_images', null=True,
        blank=True,
    )
    video_url = models.TextField(
        verbose_name='Ссылка на видео', null=True, blank=True,
    )
    position = models.PositiveIntegerField(verbose_name='Позиция', default=0)
    related_with = models.CharField(
        max_length=100, blank=True, null=True, choices=RelatedWith.choices,
    )

    objects = TestimonialManager()

    def clean(self):
        super().clean()
        if any([
            self.image and self.video_url,
            not self.image and not self.video_url
        ]):
            raise ValidationError('One of image and video url must be filled')

    def __str__(self):
        return str(self.id)

    class Meta:
        ordering = ['position']

landing/forms.py
from django import forms

from landing.models import Testimonial


class TestimonialAdminForm(forms.ModelForm):
    class Meta:
        model = Testimonial
        fields = ['image', 'video_url']


class CourseTestimonialAdminForm(TestimonialAdminForm):
    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.related_with = Testimonial.RelatedWith.COURSES
        if commit:
            instance.save()
        return instance

landing/views.py
from dataclasses import dataclass

from django.urls import reverse_lazy
from django.views.generic import DetailView, TemplateView

from landing.helpers import get_neighbors
from landing.mixins import CountdownMixin, MenuItemsMixin
from landing.models import (
    Course, CourseTestimonial, Discount, Massage, Specialist, Testimonial,
)


@dataclass
class MenuItem:
    href: str
    text: str
    anchor: bool = True


class IndexView(CountdownMixin, MenuItemsMixin, TemplateView):
    countdown_target = Discount.Target.MASSAGES
    template_name = 'landing/index.html'
    menu_items = [
        MenuItem('#about-us', 'О нас'),
        MenuItem('#services', 'Услуги'),
        MenuItem('#testimonials', 'Отзывы'),
        MenuItem('#team', 'Наши специалисты'),
        MenuItem(reverse_lazy('landing:certificates'), 'Сертификаты', False),
        MenuItem(reverse_lazy('landing:courses'), 'Обучение', False),
        MenuItem('#contacts', 'Контакты'),
    ]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'massages': Massage.objects.filter(is_active=True),
            'testimonials': Testimonial.objects.all(),
            'specialists': Specialist.objects.all(),
        })
        return context


class MassageDetailView(CountdownMixin, MenuItemsMixin, DetailView):
    countdown_target = Discount.Target.MASSAGES
    template_name = 'landing/massage_details.html'
    context_object_name = 'massage'
    menu_items = [
        MenuItem(reverse_lazy('landing:index'), 'На главную', False),
        MenuItem('#description', 'Описание'),
        MenuItem('#results', 'Наши работы'),
        MenuItem(reverse_lazy('landing:certificates'), 'Сертификаты', False),
        MenuItem(reverse_lazy('landing:courses'), 'Обучение', False),
        MenuItem('#contacts', 'Контакты'),
    ]

    def get_queryset(self):
        return Massage.objects.filter(is_active=True).prefetch_related(
            'results',
        )

    def get_context_data(self, **kwargs):
        return super().get_context_data(
            **kwargs, neighbors=get_neighbors(self.object),
        )


class CertificatesView(CountdownMixin, MenuItemsMixin, TemplateView):
    countdown_target = Discount.Target.CERTIFICATES
    template_name = 'landing/certificates.html'
    menu_items = [
        MenuItem(reverse_lazy('landing:index'), 'На главную', False),
        MenuItem('#certificates', 'Сертификаты'),
        MenuItem('#process', 'Процесс'),
        MenuItem(reverse_lazy('landing:courses'), 'Обучение', False),
        MenuItem('#contacts', 'Контакты'),
    ]


class CoursesView(CountdownMixin, MenuItemsMixin, TemplateView):
    countdown_target = Discount.Target.COURSES
    template_name = 'landing/courses.html'
    menu_items = [
        MenuItem(reverse_lazy('landing:index'), 'На главную', False),
        MenuItem('#description', 'О курсе'),
        MenuItem('#course-author', 'Об авторе'),
        MenuItem('#course-types', 'Варианты'),
        MenuItem('#testimonials', 'Отзывы'),
        MenuItem(reverse_lazy('landing:certificates'), 'Сертификаты', False),
        MenuItem('#contacts', 'Контакты'),
    ]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'courses': Course.objects.filter(is_active=True),
            'testimonials': CourseTestimonial.objects.all(),
        })
        return context

landing/templates/landing/certificates.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Подарочные сертификаты массажа{% endblock %}

{% block body %}
  <div class="promo">
    <div class="promo__image-wrap">
      <img class="promo__image" src="{% static 'img/promo/certificates.jpg' %}"
           alt="promo">
    </div>
    <div class="container">
      <header class="header">
        <a class="header__brand wow animate__animated animate__fadeIn"
           href="{% url 'landing:index' %}">Центр
          спортивного <span class="header__brand--accent">моделирующего</span>
          массажа</a>
        <button class="menu-button wow animate__animated animate__fadeIn">
          <span class="menu-button__middle-line"></span>
        </button>
        {% include 'landing/partials/header_inner.html' %}
      </header>
      <div class="promo__content">
        <h1 class="heading heading--white promo__heading wow animate__animated animate__fadeIn">
          Подарочные сертификаты</h1>
        <p class="text text--white promo__text wow animate__animated animate__fadeIn"
           data-wow-delay="0.2s">Подарочный сертификат является подарком,
          которому всегда будете рады. Он подойдёт как мужчине, так и женщине и
          придётся по вкусу получателю любого возраста и социального
          положения</p>
        {% if discount.seconds_left %}
          {% include 'partials/countdown.html' %}
          <p class="heading heading--white heading--medium promo__heading promo__heading--countdown wow animate__animated animate__fadeIn"
             data-wow-delay="0.6s">Сейчас -{{ discount.percent }}% на подарочные сертификаты</p>
        {% endif %}
        <a class="button button--cta-blue promo__button--cta move-to wow animate__animated animate__fadeIn cta-button"
           href="#cta"
           data-mt-tolerance="100"
           data-wow-delay="{% if discount.seconds_left %}0.8s{% else %}0.4s{% endif %}">Заказать</a>
        <button class="button button--scroller promo__button--scroller move-to"
                data-target="#description"></button>
      </div>
    </div>
  </div>
  {% include 'landing/partials/mobile_menu.html' %}
  <section class="section certificates" id="certificates">
    <div class="container">
      <h2 class="heading heading--section heading--centered section__heading wow animate__animated animate__fadeIn">
        Плюсы подарочного сертификата</h2>
      <div class="columns certificates__columns">
        <div class="column certificates__column">
          <div class="certificates__wrap">
            <div class="certificate-card wow animate__animated animate__fadeIn"
                 data-wow-delay="0.2s">
              <img class="certificate-card__image"
                   src="{% static 'img/certificate_cards/1.jpg' %}" alt="#">
            </div>
            <div class="certificate-card wow animate__animated animate__fadeIn"
                 data-wow-delay="0.4s">
              <img class="certificate-card__image"
                   src="{% static 'img/certificate_cards/3.jpg' %}" alt="#">
            </div>
            <div class="certificate-card wow animate__animated animate__fadeIn"
                 data-wow-delay="0.6s">
              <img class="certificate-card__image"
                   src="{% static 'img/certificate_cards/2.jpg' %}" alt="#">
            </div>
          </div>
        </div>
        <div class="column certificates__column">
          <ul class="certificates__list">
            <li class="text wow animate__animated animate__fadeIn"
                data-wow-delay="0.2s">Универсальность
            </li>
            <li class="text wow animate__animated animate__fadeIn"
                data-wow-delay="0.4s">Возможность выбрать сумму сертификата
            </li>
            <li class="text wow animate__animated animate__fadeIn"
                data-wow-delay="0.6s">Срок действия 3 месяца
            </li>
            <li class="text wow animate__animated animate__fadeIn"
                data-wow-delay="0.8s">Стильная подарочная упаковка
            </li>
          </ul>
        </div>
      </div>
    </div>
  </section>
  <section class="section process" id="process">
    <div class="container">
      <h2 class="heading heading--section section__heading wow animate__animated animate__fadeIn">
        Процесс оформления</h2>
      <div class="columns columns--wrap process__columns">
        <div
            class="column process__column wow animate__animated animate__fadeIn"
            data-wow-delay="0.2s">
          <div class="process-card process-card--card">
            <p class="process-card__desc">Выбирайте сертификат на подходящую
              Вам сумму. Произведите оплату по нашим реквизитам</p>
          </div>
        </div>
        <div
            class="column process__column wow animate__animated animate__fadeIn"
            data-wow-delay="0.4s">
          <div class="process-card process-card--gift">
            <p class="process-card__desc">Мы доставим его получателю в
              оговорённый срок и время в подарочной упаковке</p>
          </div>
        </div>
        <div
            class="column process__column wow animate__animated animate__fadeIn"
            data-wow-delay="0.6s">
          <div class="process-card process-card--care">
            <p class="process-card__desc">Ваш подарок обязательно понравится и
              даст понять о вашей заботе и пожелании</p>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="why-we wow animate__animated animate__fadeIn">
    <div class="container why-we__container">
      <div class="why-we__image-wrap"></div>
      <div class="why-we__content-wrap">
        <h2 class="heading heading--section heading--white why-we__heading">
          Почему «Атлант»?</h2>
        <p class="why-we__text text--white">
          <span class="why-we__text--bold">4 года</span>
          успешной работы
        </p>
        <p class="why-we__text text--white">
          <span class="why-we__text--bold">3500</span>
          довольных клиентов
        </p>
        <p class="why-we__text text--white">
          Техники массажа, которые
          <span class="why-we__text--bold">дают результат</span>
        </p>
        <p class="why-we__text text--white">
          <span class="why-we__text--bold">Индивидуальное решение</span>
          запроса каждого клиента
        </p>
      </div>
    </div>
  </section>
  <section class="cta-blue wow animate__animated animate__fadeIn" id="cta">
    <div class="container">
      <div class="columns cta-blue__columns">
        <div class="column cta-blue__column cta-blue__column--left">
          <h2 class="heading heading--section heading--white cta-blue__heading">
            Остались вопросы?<br>С удовольствием ответим</h2>
          <p class="text text--white cta-blue__text">Оставьте свои контакты и
            наш менеджер перезвонит вам</p>
        </div>
        <div class="column cta-blue__column cta-blue__column--right">
          <form class="client-request-form"
                action="{% url 'clients:create' %}">
            <div class="form form--vertical">
              <input type="hidden" name="tag" value="{{ request.path }}">
              <label class="form__item">
                <input class="form__input" type="text" name="name"
                       placeholder="Введите ваше имя" id="cta-input">
              </label>
              <label class="form__item">
                <input class="form__input phone-mask" type="text"
                       placeholder="+_ (___) ___-__-__" name="phone_number">
              </label>
              <button class="button button--cta cta-blue__button">Заказать
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

{% block extra_bottom_imports %}
  <script src="{% static 'js/cta.js' %}"></script>
  <script src="{% static 'js/client_request_form.js' %}"></script>
{% endblock %}

landing/templates/landing/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Центр спортивного и моделирующего массажа Атлант{% endblock %}

{% block body %}
  <div class="promo">
    <div class="promo__image-wrap">
      <img class="promo__image" src="{% static 'img/promo/index.jpg' %}"
           alt="promo">
    </div>
    <div class="container">
      <header class="header">
        <a class="header__brand wow animate__animated animate__fadeIn"
           href="{% url 'landing:index' %}">Центр
          спортивного <span class="header__brand--accent">моделирующего</span>
          массажа</a>
        <button class="menu-button wow animate__animated animate__fadeIn">
          <span class="menu-button__middle-line"></span>
        </button>
        {% include 'landing/partials/header_inner.html' %}
      </header>
      <div class="promo__content">
        <h1 class="heading heading--white promo__heading wow animate__animated animate__fadeIn">
          Массаж в Алматы от профессионалов</h1>
        <p class="text text--white promo__text wow animate__animated animate__fadeIn"
           data-wow-delay="0.2s">
          Сертифицированные мастера, работающие только на результат</p>
        {% if discount.seconds_left %}
          {% include 'partials/countdown.html' %}
          <p class="heading heading--white heading--medium promo__heading promo__heading--countdown wow animate__animated animate__fadeIn"
             data-wow-delay="0.6s">Сейчас -{{ discount.percent }}% на любой вид
            массажа</p>
        {% endif %}
        <a class="button button--cta promo__button--cta move-to wow animate__animated animate__fadeIn cta-button"
           href="#cta"
           data-mt-tolerance="100"
           data-wow-delay="{% if discount.seconds_left %}0.8s{% else %}0.4s{% endif %}">Записаться</a>
        <button class="button button--scroller promo__button--scroller move-to"
                data-target="#about-us"></button>
      </div>
    </div>
  </div>
  {% include 'landing/partials/mobile_menu.html' %}
  <section class="section about-us" id="about-us">
    <div class="container">
      <h2 class="heading heading--section section__heading wow animate__animated animate__fadeIn">
        О
        нас</h2>
      <div class="columns about-us__columns">
        <div data-wow-delay="0.2s"
             class="column about-us__column about-us__column--first wow animate__animated animate__fadeIn">
          <p class="text">За <span class="text--accent">3 года</span> работы центра более <span
              class="text--accent">3000</span> довольных клиентов</p>
          <br>
          <p class="text">Массаж от Центра спортивного моделирующего массажа <span
              class="text--accent">«Atlant»</span> — это:</p>
          <br>
          <ul class="text">
            <li>• Ваше здоровое тело</li>
            <li>• Эффективные решения физических и эстетических проблем тела</li>
            <li>• Без использования химических и механических средств или хирургических
              вмешательств
            </li>
          </ul>
          <br>
          <p class="text">Многолетний опыт работы позволил нам разработать особые методики массажа,
            которые дают <span class="text--accent">гарантированный результат</span> в борьбе с
            усталостью, болями, проблемными зонами и лишними сантиметрами</p>
          <br>
          <p class="text">Наше отличие от других кабинетов массажа в том, что мы делаем акцент
            именно на пользе массажа, а не на пафосе бренда, ненужных манипуляций и декоре
            помещений</p>
          <br>
          <p class="text">Это позволяет радовать клиентов <span class="text--accent">высоким качеством</span>
            и <span class="text--accent">приятными ценами</span></p>
        </div>
        <div
            class="column about-us__column wow animate__animated animate__fadeIn"
            data-wow-delay="0.4s">
          <img class="about-us__image" src="{% static 'img/logo.svg' %}"
               alt="atlant">
        </div>
      </div>
    </div>
  </section>
  {% include 'landing/partials/massages.html' %}
  <section class="section reasons">
    <div class="container">
      <h2 class="heading heading--section section__heading wow animate__animated animate__fadeIn">
        6
        причин записаться<br>к нам на массаж
        <span class="heading--accent wow animate__animated animate__fadeIn"
              data-wow-delay="0.2s">уже сегодня</span>
      </h2>
      <div class="columns columns--wrap reasons__columns">
        <div
            class="column reasons__column wow animate__animated animate__fadeIn">
          <div class="reason-card reason-card--pain">
            <p class="reason-card__desc">Вас беспокоят боли в спине, шее?</p>
          </div>
        </div>
        <div
            class="column reasons__column wow animate__animated animate__fadeIn"
            data-wow-delay="0.2s">
          <div class="reason-card reason-card--rest">
            <p class="reason-card__desc">Вам давно не удавалось отдохнуть
              морально?</p>
          </div>
        </div>
        <div
            class="column reasons__column wow animate__animated animate__fadeIn"
            data-wow-delay="0.4s">
          <div class="reason-card reason-card--energy">
            <p class="reason-card__desc">Ваша работоспособность упала, не
              хватает бодрости и
              сил?</p>
          </div>
        </div>
        <div
            class="column reasons__column wow animate__animated animate__fadeIn"
            data-wow-delay="0.6s">
          <div class="reason-card reason-card--stress">
            <p class="reason-card__desc">Вы стали раздражительны из-за
              постоянного стресса?</p>
          </div>
        </div>
        <div
            class="column reasons__column wow animate__animated animate__fadeIn"
            data-wow-delay="0.8s">
          <div class="reason-card reason-card--care">
            <p class="reason-card__desc">Вы заботитесь о своем физическом и
              психологическом
              здоровье и выбираете профилактику?</p>
          </div>
        </div>
        <div
            class="column reasons__column wow animate__animated animate__fadeIn"
            data-wow-delay="1s">
          <div class="reason-card reason-card--fat">
            <p class="reason-card__desc">Вы хотите уменьшить объемы, избавиться
              от целлюлита?</p>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="cta-blue-image wow animate__animated animate__fadeIn"
           id="cta">
    <div class="container cta-blue-image__container">
      <div class="cta-blue-image__form-wrap">
        <h2 class="heading heading--white cta-blue-image__heading">Сейчас у нас супер акции!</h2>
        <form class="client-request-form" action="{% url 'clients:create' %}">
          <div class="form form--vertical">
            <input type="hidden" name="tag" value="{{ request.path }}">
            <label class="form__item">
              <input class="form__input" type="text" id="cta-input"
                     placeholder="Введите ваше имя" name="name">
            </label>
            <label class="form__item">
              <input class="form__input phone-mask" type="text"
                     placeholder="+_ (___) ___-__-__" name="phone_number">
            </label>
            <button class="button button--cta cta-blue__button" type="submit">
              Узнать об акциях
            </button>
          </div>
        </form>
      </div>
      <div class="cta-blue-image__image-wrap"></div>
    </div>
  </section>
  {% include 'landing/partials/testimonials.html' %}
  <section class="cta-blue wow animate__animated animate__fadeIn">
    <div class="container">
      <div class="columns cta-blue__columns">
        <div class="column cta-blue__column cta-blue__column--left">
          <h2 class="heading heading--section heading--white cta-blue__heading">
            Прямо сейчас скидки на все процедуры</h2>
          <p class="text text--white cta-blue__text">Оставьте свои контакты и
            наш менеджер перезвонит вам</p>
        </div>
        <div class="column cta-blue__column cta-blue__column--right">
          <form class="client-request-form"
                action="{% url 'clients:create' %}">
            <div class="form form--vertical">
              <input type="hidden" name="tag" value="{{ request.path }}">
              <label class="form__item">
                <input class="form__input" type="text" name="name"
                       placeholder="Введите ваше имя">
              </label>
              <label class="form__item">
                <input class="form__input phone-mask" type="text"
                       placeholder="+_ (___) ___-__-__" name="phone_number">
              </label>
              <button class="button button--cta cta-blue__button"
                      type="submit">
                Записаться сейчас
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
  {% include 'landing/partials/specialists.html' %}
  <section class="cta-image wow animate__animated animate__fadeIn">
    <div class="container">
      <h2 class="heading heading--section heading--white cta-image__heading">
        Остались вопросы?</h2>
      <p class="text text--white cta-image__text">Оставьте свои контакты и наш
        менеджер перезвонит вам</p>
      <form class="client-request-form" action="{% url 'clients:create' %}">
        <div class="form">
          <input type="hidden" name="tag" value="{{ request.path }}">
          <div class="columns cta-image__columns">
            <div class="column cta-image__column">
              <label class="form__item">
                <input class="form__input" type="text" name="name"
                       placeholder="Введите ваше имя">
              </label>
            </div>
            <div class="column cta-image__column">
              <label class="form__item">
                <input class="form__input phone-mask" type="text"
                       placeholder="+_ (___) ___-__-__" name="phone_number">
              </label>
            </div>
            <div class="column cta-image__column">
              <label class="form__item">
                <button class="button button--cta cta-image__button">Записаться
                  сейчас
                </button>
              </label>
            </div>
          </div>
        </div>
      </form>
    </div>
  </section>
{% endblock %}

{% block extra_bottom_imports %}
  <script src="{% static 'js/index/carousels.js' %}"></script>
  <script src="{% static 'js/index/massage_cards.js' %}"></script>
  <script src="{% static 'js/cta.js' %}"></script>
  <script src="{% static 'js/client_request_form.js' %}"></script>
{% endblock %}